ballot_store/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls')), 
    path('api/', include('rest_api.urls'))
]

store/urls.py
from django.urls import path
from . import views

app_name = 'store'
urlpatterns = [
    path('', views.home, name='home'), 
    path('datos_personales/', views.datos_personales, name='datos_personales'), 
    path('epayco_confirmation', views.epayco_confirmation, name="epayco_confirmation"),
    path('bill/', views.fetch_api, name='fetch'), 
]
    
    
    
    
    

store/models.py
from django.db import models
from django.core.exceptions import ValidationError
from django.core.validators import MinValueValidator, MaxValueValidator
from phonenumber_field.modelfields import PhoneNumberField
from django.utils import timezone
from datetime import timedelta
from django.db.models.signals import post_save
from django.contrib import messages

class ComplexClient(models.Model):
    phone_number = PhoneNumberField()
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    

class Sociedad(models.Model):
    name = models.CharField('Nombre', max_length=100)
    
    def __str__(self):
        return self.name

class Rifa(models.Model):
    display_percentage = models.BooleanField('Mostrar porcentaje de balotas vendidas', default=False)
    is_active = models.BooleanField('Está activa', default=False)
    society = models.ForeignKey(Sociedad, on_delete=models.CASCADE, verbose_name='Sociedad')
    name = models.CharField('Nombre de la rifa', max_length=100)
    prize = models.CharField('Premio', max_length=200)
    description = models.TextField('Descripción', max_length=1000, blank=True, null=True)
    lottery_date = models.DateField('Fecha de sorteo')
    ballot_price = models.PositiveIntegerField('Precio de las balotas', default=10000)    
    min_number = models.IntegerField('Número mínimo', validators=[MinValueValidator(0)], default=0)
    max_number = models.IntegerField('Número máximo', validators=[MinValueValidator(0)])
    step = models.IntegerField('Paso', validators=[MinValueValidator(1)], default=1)
    ballot_unavailable_time = models.DurationField('Tiempo de inhabilidad de las balotas', default=timedelta(minutes=10))
    
    def save(self):  
        n = (self.max_number+1 - self.min_number) // self.step   
        if self.min_number <= self.max_number and n > 0:
            super().save()
        else:
            raise ValidationError('El número máximo no puede ser menor al mínimo.')
    
    def __str__(self):
        return self.name 
        
class Cliente(models.Model):
    first_name = models.CharField('Nombre', max_length=100)
    last_name = models.CharField('Apellido', max_length=100)
    email = models.CharField('Correo electrónico', max_length=100)
    phone_number = models.PositiveIntegerField('Número de celular')
    
    def __str__(self):
        return f"{self.first_name} / cel: {self.phone_number} / id: {self.id}"
    
class Descuento(models.Model):
    lottery= models.ForeignKey(Rifa, on_delete=models.CASCADE, verbose_name='Sorteo')
    status_options = [(True, 'Habilitado'), (False, 'Inhabilitado')]
    PERCENTAGE_VALIDATOR = [MinValueValidator(0), MaxValueValidator(100)]
    status = models.BooleanField('Estado', choices=status_options, default=True)
    discount_code = models.CharField('Código de descuento', max_length=100)
    percentage = models.DecimalField('Porcentaje de descuento', max_digits=3, decimal_places=0, validators=PERCENTAGE_VALIDATOR)
    
    def __str__(self):
        return ''.join([str(self.percentage), '%'])
    
class Transaccion(models.Model):
    status_options = [(0, 'Pendiente'), (1, 'Efectuada'), (2, 'Vencida')]
    
    status = models.IntegerField('Estado', choices=status_options, default=0)
    client = models.OneToOneField(Cliente, on_delete=models.DO_NOTHING, default=None, null=True, blank=True, verbose_name='Cliente')
    discount = models.ForeignKey(Descuento, on_delete=models.SET_DEFAULT, default=None, null=True, blank=True, verbose_name='Descuento')
    payment_link = models.CharField('Link de pago', max_length=100, default=None, null=True, blank=True)
    value_1 = models.IntegerField('Valor inicial', default=None, null=True, blank=True)
    value_2 = models.IntegerField('Valor final', validators=[MinValueValidator(0)], default=None, null=True, blank=True)
    validated_value = models.PositiveIntegerField('Valor validado', default=None, null=True, blank=True)
    created_at = models.DateTimeField('Creado', default=timezone.now)
    valid_until = models.DateTimeField('Válido hasta', default=None, null=True, blank=True)
    x_ref_payco = models.CharField(max_length=100, default=None, null=True, blank=True)
    x_description = models.CharField(max_length=100, default=None, null=True, blank=True)
    x_response = models.CharField(max_length=100, default=None, null=True, blank=True)
    
    def __str__(self):
        return f"Transacción {self.id}"
    
class Balota(models.Model):
    number = models.IntegerField('Número')
    price = models.PositiveIntegerField('Precio', default=10000)
    selected = models.BooleanField('Seleccionada', default=False)
    transaction = models.ForeignKey(Transaccion, on_delete=models.SET_DEFAULT, default=None, null=True, blank=True, verbose_name='Transacción')
    unavailable_time = models.DurationField('Tiempo de inhabilidad', default=(timedelta(minutes=15)))
    lottery = models.ForeignKey(Rifa, on_delete=models.CASCADE, verbose_name='Rifa')
    
    def __str__(self):
        return str(self.number)
    
class EpaycoLateConfirmation(models.Model):
    status_options = [(0, 'OK'), (1, 'Por resolver')] 
    
    transaction = models.OneToOneField(Transaccion, on_delete=models.CASCADE, default=None, null=True, verbose_name='Transacción')   
    status = models.IntegerField('Estado', choices=status_options, default=0)
    json_data = models.TextField('Datos Json', default='', null=True, blank=True)
    description = models.TextField('Descripción', default='', null=True, blank=True)
    
    def __str__(self):
        return 'Para ' + str(self.transaction)                 

store/forms.py
from django import forms
from .models import Cliente

class ClienteForm(forms.ModelForm):
    class Meta:
        model = Cliente
        fields = ['first_name', 'last_name', 'email', 'phone_number']
        widgets = {
            'first_name': forms.TextInput(attrs={
                'class': 'field__input', 'id': 'first-name'
                }),
            'last_name': forms.TextInput(attrs={
                'class': 'field__input', 'id': 'last-name'
                }),
            'email': forms.EmailInput(attrs={
                'class': 'field__input', 'id': 'email'
                }),
            'phone_number': forms.TextInput(attrs={
                'class': 'field__input', 'id': 'phone-number'
                }), 
        }

store/views.py
import json
import requests
import math
from datetime import timedelta, datetime, date
from django.utils import timezone
from django.conf import settings
from django.shortcuts import render
from django.http import HttpResponse, JsonResponse
from django.contrib import messages
from django.shortcuts import redirect
from django.views.generic import ListView
from .forms import ClienteForm
from .models import Cliente, Balota, Transaccion, Descuento, EpaycoLateConfirmation, Rifa, Sociedad
from django.views.decorators.csrf import csrf_exempt
from django.urls import reverse
from .strings import message_mapper 
import os
from dotenv import load_dotenv


load_dotenv()


# ENVIRONMENT VARIABLES

society_id = int(os.getenv('SOCIETY_ID'))

token = os.getenv('TOKEN')

epayco_login_url = os.getenv('EPAYCO_LOGIN_URL')

epayco_create_link_url = os.getenv('EPAYCO_CREATE_LINK_URL')

epayco_transaction_detail_url = os.getenv('EPAYCO_TRANSACTION_DETAIL_URL')


# EPAYCO RESPONSE LINKS

base_url = f"http{os.getenv('HTTP_SAFE')}://{os.getenv('DOMAIN')}{os.getenv('LOCAL_PORT')}"

confirmation_url = f"{base_url}/epayco_confirmation"

response_base_url = f"{base_url}"


# VARIABLES AND FUNCTIONS

society_creation_date = date(2018, 2, 6)

try:
    society = Sociedad.objects.get(id=society_id)
except:
    society = None

url_base = '//'.join([confirmation_url.split('/')[0], confirmation_url.split('/')[2]])

from .tools import (
    make_transaction_description, 
    get_values_from_transaction_description, 
    get_percentage_to_display
)
     
ePayco_confirmation_time = timedelta(hours=3, minutes=30)

def epayco_get_token():
    # Login request
    url = epayco_login_url
    payload = ""
    headers = {
        'Authorization': 'Basic ' + token,
        'Content-Type': 'application/json'
    }
    response = requests.request("POST", url, headers=headers, data=payload)
    given_token = response.json()['token']
    return given_token

def epayco_get_transaction_link(value_2, transaction, ballots, client):
    url = epayco_create_link_url
    payload = json.dumps({
        "quantity": 1,
        "onePayment": True,
        "amount": str(value_2),
        "currency": "COP",
        "id": 0,  # Debe ser único, si se envia cero, epayco genera uno automaticamente
        "base": "0",
        "description": make_transaction_description(ballots, transaction), 
        "title": "Link de cobro",
        "typeSell": "2", # 2 via link
        "tax": "0", 
        "urlConfirmation": confirmation_url, 
        "urlResponse": response_base_url + '?tr_pk=' + str(transaction.id), 
        "methodConfirmation": "GET", # request.method = 'POST' anyway ?tr_id=
        "expirationDate": timezone.localtime(transaction.valid_until).strftime('%Y-%m-%d %H:%M:%S'),    # Format Date Time UTC payment link expiration date 
    })
    
    headers = {
        'Content-Type': 'application/json', 
        'Authorization': 'Bearer '+ epayco_get_token()
    }

    response = requests.request("POST", url, headers=headers, data=payload)
    link = response.json()['data']['routeLink']
    return link

def epayco_get_transaction_details(x_ref_payco):
    url = epayco_transaction_detail_url

    payload = json.dumps({
    "filter": {
        "referencePayco": int(x_ref_payco)
    }
    })
    headers = {
    'Content-Type': 'application/json', 
    'Authorization': 'Bearer '+ epayco_get_token()
    }

    response = requests.request("GET", url, headers=headers, data=payload)
    
    return response.json()['data']

def unbind_ballots(lottery):
    
    # hopeless_transactions = Transaccion.objects.filter(estado=0).filter(valid_until__lte=timezone.now()-ePayco_confirmation_time)
    # for transaction in hopeless_transactions:
    #     for ballot in transaction.balota_set.all():
    #         ballot.transaccion = None
    #         ballot.save()
            
    #     transaction.estado = 2
    #     transaction.save()
    
    
    lottery_ballots = list(Balota.objects.filter(lottery=lottery))
    lottery_transactions = []
    for ballot in lottery_ballots:
        if ballot.transaction != None and not ballot.transaction in lottery_transactions:
            lottery_transactions.append(ballot.transaction)
    hopeless_transactions = []
    for transaction in lottery_transactions:
        if transaction.status == 0 and transaction.valid_until < timezone.now()-ePayco_confirmation_time:
            hopeless_transactions.append(transaction)
    for transaction in hopeless_transactions:
        for ballot in transaction.balota_set.all():
            ballot.transaction = None
            ballot.save()
            
        transaction.status = 2
        transaction.save()

def handle_transaction_response(data):
    
    """
    Epayco_response gets data from a simple request 
    but epayco_confirmation makes a more complex process since it doesn't
    have that encoded ref_payco
    """
    
    purchase_details = get_values_from_transaction_description(data['x_description'])
    x_response = data['x_response']
    transaction = Transaccion.objects.get(id=purchase_details['transaction_id'])
    transaction.x_description = data['x_description']
    transaction.x_ref_payco = data['x_ref_payco']
    transaction.validated_value = int(data['x_amount'])
    transaction.x_response = x_response
    
    transaction.save()
    
    if transaction.status == 0:
        
        if transaction.x_response == 'Pendiente':
            pass
        elif transaction.x_response == 'Rechazada':
            pass
        elif transaction.x_response == 'Fallida':
            pass
        elif transaction.x_response == 'Aceptada':
            transaction.status = 1
    
    
    elif transaction.status == 1:
        pass
    
    
    elif transaction.status == 2:
        if transaction.x_response == 'Pendiente':
            pass
        elif transaction.x_response == 'Rechazada':
            pass
        elif transaction.x_response == 'Fallida':
            pass
        elif transaction.x_response == 'Aceptada':
            
            # late confirmation
            late_confirmation = EpaycoLateConfirmation(
                transaction=transaction, json_data=json.dumps(data)
            )
        
            unavailable_ballot_ids = []
            
            ballots = [Balota.objects.get(id=id) for id in purchase_details['ballot_ids']]
            
            for ballot in ballots:
                
                if ballot.transaction == None or ballot.transaction == transaction:
                    ballot.transaction = transaction
                    ballot.save()
                
                else:
                    late_confirmation.status = 1
                    unavailable_ballot_ids.append(ballot.id)
            
            description = {'unavailable_ballot_ids': unavailable_ballot_ids}
            late_confirmation.description = json.dumps(description)
            transaction.status = 1
            late_confirmation.save() 
    
    
    transaction.save()
    
    
# VIEWS 

def home(request):
    js_variables = {'msg':['', '']}
    
    if 'tr_pk' in request.GET.dict().keys():
        
        """" Epeyco response """
        transaction = Transaccion.objects.get(id=int(request.GET.dict()['tr_pk']))

        if not transaction.payment_link:  
            if transaction.status == 1:
                js_variables['msg'] = message_mapper['Aceptada']
                
        else:
            encoded_ref_payco = request.GET.dict()['ref_payco']
            url = 'https://secure.epayco.co/validation/v1/reference/' + encoded_ref_payco
            response = requests.request("GET", url)
            data = response.json()['data']
            data['view_link'] = ''.join([url_base, request.get_full_path()])
            
            handle_transaction_response(data)
            
            js_variables['msg'] = message_mapper[data['x_response']]
            
            if data['x_response'] == 'Rechazada' or data['x_response'] == 'Fallida':
                js_variables['link'] = transaction.payment_link
    
    if 'msg' in request.GET.dict().keys():
        key = request.GET.dict()['msg']
        js_variables['msg'] = message_mapper[key]
        
    try:
        lottery = society.rifa_set.filter(is_active=True).first()
    except:
        lottery = None
    
    js_variables['lottery_id'] = lottery.id
    
    unbind_ballots(lottery)
    
    try:
        js_variables['ballot_price'] = Balota.objects.filter(lottery=lottery).first().price
    except:
        js_variables['ballot_price'] = 1000000
    
    js_variables['ballot_fetch_url'] = f"{base_url}/api/get_ballots"
    
    
        
    
    context = {
        'js_variables': js_variables, 
        'years_on_dutty': (datetime.now().date() - society_creation_date).days // 365, 
        'days_left_to_play': (lottery.lottery_date - datetime.today().date()).days
    }
    
    if lottery.display_percentage:
        percentage = len(Balota.objects.filter(
                lottery=lottery
            ).filter(transaction__status=1))/len(Balota.objects.filter(
                lottery=lottery
            ))*100
        
        # context['sold_ballot_percentage'] = get_percentage_to_display(percentage)
        
        context['sold_ballot_percentage'] = int(percentage)
    
    return render(request, 'store/index.html', context)
    
def datos_personales(request):
    if request.method == 'POST':
        try:
            balota_ids = dict(request.POST).get('id')
            ballots = [Balota.objects.get(id=id) for id in balota_ids]
            subtotal = 0
            for ballot in ballots:
                subtotal += ballot.price
            js_variables = {
                'bId': balota_ids, 
                'code_validation_url': f"{base_url}/api/code_validation", 
                'link_creation_url': f"{base_url}/bill/"
            }
            context = {'js_variables': js_variables, 'ballots': ballots, 'subtotal': subtotal}

templates/store/form.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>El Altar - Taquería</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href={% static "assets/img/logo32.png" %} rel="icon">
  <link href={% static "assets/img/logo180.png" %} rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href={% static "assets/vendor/aos/aos.css" %} rel="stylesheet">
  <link href={% static "assets/vendor/bootstrap/css/bootstrap.min.css" %} rel="stylesheet">
  <link href={% static "assets/vendor/bootstrap-icons/bootstrap-icons.css" %} rel="stylesheet">
  <link href={% static "assets/vendor/boxicons/css/boxicons.min.css" %} rel="stylesheet">
  <link href={% static "assets/vendor/glightbox/css/glightbox.min.css" %} rel="stylesheet">
  <link href={% static "assets/vendor/swiper/swiper-bundle.min.css" %} rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href={% static "assets/css/style.css" %} rel="stylesheet">
</head>

<body>

  <!-- ======= Mobile nav toggle button ======= -->
  <i class="bi bi-list mobile-nav-toggle d-xl-none"></i>

  <!-- ======= Header ======= -->
  <header id="header">
    <div class="d-flex flex-column">

      <div class="profile">
        <img src={% static "assets/img/short-600.jpg" %} alt="" class="img-fluid rounded-circle">
        <h1 class="text-light"><a href={% url 'store:home' %}>El Altar - Taquería</a></h1>
        <div class="social-links mt-4 text-center">
          
          <a href="#" class="facebook"><i class="bx bxl-facebook"></i></a>
          <a href="https://instagram.com/elaltar_?igshid=YmMyMTA2M2Y=" class="instagram"><i class="bx bxl-instagram"></i></a>
          <a href="https://wa.me/573042977894" class="whatsapp"><i class="bx bxl-whatsapp"></i></a>
          
        </div>
      </div>
      <br>
      <hr style="color:#fff;">
      <nav id="navbar" class="nav-menu navbar">
        <ul>
          <li><a href={% url 'store:home' %} class="nav-link scrollto active"><i class="bx bx-home"></i> <span>Home</span></a></li>
          <li><a href="{% url 'store:home' %}#services" class="nav-link scrollto"><i class="bx bx-heart"></i> <span>Quiero tacos GRATIS!</span></a></li>
          <li><a href="#" class="nav-link scrollto"><i class="bx bx-phone"></i> <span>(+57) 300-00-00</span></a></li>
          <!-- <li><a href="#portfolio" class="nav-link scrollto"><i class="bx bx-book-content"></i> <span>Portfolio</span></a></li>
          <li><a href="#services" class="nav-link scrollto"><i class="bx bx-server"></i> <span>Services</span></a></li>
          <li><a href="#contact" class="nav-link scrollto"><i class="bx bx-envelope"></i> <span>Contact</span></a></li> -->
        </ul>
      </nav><!-- .nav-menu -->
    </div>
  </header><!-- End Header -->

  <main id="main">

    <!-- ======= Breadcrumbs ======= -->
    <section class="breadcrumbs">
      <div class="container">

        <div class="d-flex justify-content-between align-items-center">
          <h2>Facturación</h2>
          <ol>
            <li><a href={% url 'store:home' %}>Home</a></li>
            <li>Facturación</li>
          </ol>
        </div>

      </div>
    </section><!-- End Breadcrumbs -->

        <!-- ======= Contact Section ======= -->
        <section id="contact" class="contact">
          <div class="container">
    
            <!-- <div class="section-title">
              <h2>Contact</h2>
              <p>Magnam dolores commodi suscipit. Necessitatibus eius consequatur ex aliquid fuga eum quidem. Sit sint consectetur velit. Quisquam quos quisquam cupiditate. Et nemo qui impedit suscipit alias ea. Quia fugiat sit in iste officiis commodi quidem hic quas.</p>
            </div> -->
    
            <div class="row align-items-center" data-aos="fade-in">
    
              <div class="col-lg-5 d-flex align-items-stretch">
                <div class="info">
                  <div class="address">
                    <i class="bi bi-receipt"></i>
                    <h4>Subtotal</h4>
                    <p id="bill-subtotal">$ {{ subtotal }}</p>
                  </div>
    
                  <div class="email">
                    <i class="bi bi-percent"></i>
                    <h4>Descuento</h4>


                    <!-- ======= Elementos necesarios para la validación del código. ids necesarios======= -->                    
                    <div class="row">
                      <div class="input-group mb-3">
                        <input type="text" id="discount_code" name="discount_code" value="" class="form-control" placeholder="Código de descuento" aria-label="Código de descuento" aria-describedby="codigo-descuento">
                        <button type="button" class="btn btn-dark" id="code-validator">Validar</button>
                      </div>
                    </div>
                    <div class="row">
                      <div class="col-md-10">
                        <p id="discount-code-message"></p> 
                      </div>
                    </div>
                  </div>
    
                  <div class="phone">
                    <i class="bi bi-cash-coin"></i>
                    <h4>Total</h4>
                    <p id="bill-total">$ {{ subtotal }}</p>
                  </div>
                </div>
    
              </div>
    
              <div class="col-lg-7 mt-5 mt-lg-0 d-flex align-items-stretch">
                <form action={% url 'store:fetch' %} method="post" role="form" class="php-email-form" id="personal-data-form">
                  {% csrf_token %}
                  <div class="row">
                    <div class="form-group col-md-6">
                      <label for="name">Nombre</label>
                      <input type="text" name="first_name" class="form-control" id="name" required>
                    </div>
                    <div class="form-group col-md-6">
                      <label for="name">Apellidos</label>
                      <input type="text" class="form-control" name="last_name" id="email" required>
                    </div>
                  </div>
                  <div class="form-group">
                    <label for="name">Email</label>
                    <input type="email" class="form-control" name="email" id="subject" required>
                  </div>
                  <div class="form-group">
                    <label for="name">Celular</label>
                    <input type="number" class="form-control" name="phone_number" required></textarea>
                  </div>
                  <div class="my-3">
                    <div class="loading">Cargando</div>
                    <div class="error-message">Error en formulario</div>
                    <div class="sent-message">Formulario válido</div>
                  </div>
                  <div class="text-center"><button type="submit" id="form-submitter">Pagar</button></div>
                </form>
              </div>
    
            </div>
    
          </div>
        </section><!-- End Contact Section -->

  </main><!-- End #main -->

  <!-- ======= Footer ======= -->
  <footer id="footer">
    <div class="container">
      <div class="copyright">
        <strong><span>Medellín - Colombia</span></strong>
      </div>
      <div class="credits">
        <!-- All the links in the footer should remain intact. -->
        <!-- You can delete the links only if you purchased the pro version. -->
        <!-- Licensing information: https://bootstrapmade.com/license/ -->
        <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/iportfolio-bootstrap-portfolio-websites-template/ -->
        2023
      </div>
    </div>
  </footer><!-- End  Footer -->

  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  <!-- Vendor JS Files -->
  <script src={% static "assets/vendor/purecounter/purecounter_vanilla.js" %}></script>
  <script src={% static "assets/vendor/aos/aos.js" %}></script>
  <script src={% static "assets/vendor/bootstrap/js/bootstrap.bundle.min.js" %}></script>
  <script src={% static "assets/vendor/glightbox/js/glightbox.min.js" %}></script>
  <script src={% static "assets/vendor/isotope-layout/isotope.pkgd.min.js" %}></script>
  <script src={% static "assets/vendor/swiper/swiper-bundle.min.js" %}></script>
  <script src={% static "assets/vendor/typed.js/typed.min.js" %}></script>
  <script src={% static "assets/vendor/waypoints/noframework.waypoints.js" %}></script>
  <script src={% static "assets/vendor/php-email-form/validate.js" %}></script>

  <!-- Template Main JS File -->
  <script type="text/javascript" src={% static 'assets/js/main.js' %}></script>
  
  <!-- Page specific JS File -->
  {{ js_variables|json_script:'js-variables' }}
  <script type="text/javascript" src={% static "assets/js/form.js" %}></script>
</body>

</html>

templates/store/lotery_list.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Loterías{% endblock title %}

{% block content %}


<form action="/balotas/" method='get'>

    {% for lottery in object_list %}
    <input type="submit" name="lottery_id" value={{ lottery.id }}>
    {% endfor %}

</form>

{% endblock content %}